{application,peer_system,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"peer_system"},
              {modules,['Elixir.App','Elixir.BEB','Elixir.DAC','Elixir.DNS',
                        'Elixir.FD','Elixir.LPL','Elixir.LRB','Elixir.Peer',
                        'Elixir.System7']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
