{application,peer_system,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"peer_system"},
              {modules,['Elixir.App','Elixir.BEB','Elixir.DAC','Elixir.DNS',
                        'Elixir.LPL','Elixir.Peer','Elixir.RB',
                        'Elixir.System6']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
